Add files via upload
ShizaIncorp/KomisarViktor pull request #1
Opened 2024-10-18 14:19 UTC by ShizaIncorp

2024-10-19 17:16 UTC, rmushkin requested changes
Пожалуйста, поправьте файлы. Будут вопросы - пишите.

2024-10-19 17:16 UTC, rmushkin commented on Лабораторная 1/Task1.py
Пожалуйста, запрограммируйте это так, чтобы поиск None был автоматическим (т. е. нельзя хардкодить индекс пропуска, считайте, что он каждый раз может быть разным).

2024-10-19 17:16 UTC, rmushkin commented on Лабораторная 1/Task1.py
> +numbers[4] = sum(numbers)/len(numbers)
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): математические операторы должны окружаться пробелами

2024-10-19 17:16 UTC, rmushkin commented on Лабораторная 1/Task2.py
> +info_vol = 1.44*1024*1024
PEP8!

2024-10-19 17:16 UTC, rmushkin commented on Лабораторная 1/Task2.py
> +one_book_memory = 4*total_sym*numbers_str*total_page
PEP8!

2024-10-19 17:16 UTC, rmushkin commented on Лабораторная 1/Task2.py
> +total_book = round(info_vol//one_book_memory, )
`round` использовать неправильно, т. к. при математическом округлении может получиться число, большее реального нецелого значения - а поместившаяся не целиком книга поместившейся считаться не может.

2024-10-19 18:27 UTC, ShizaIncorp commented on Лабораторная 1/Task1.py
Здравствуйте, так если использовать синтаксис только из первого раздела это в принципе будет крайне сложно сделать, нельзя же применять оператор "if" и операторы "for ...", "while ...", это же получается делать сравнение каждого элемента в ручную?

2024-10-19 18:33 UTC, ShizaIncorp commented on Лабораторная 1/Task2.py
> +total_book = round(info_vol//one_book_memory, )
То есть использовать лучше слайсирование?

2024-10-19 19:02 UTC, ShizaIncorp commented on Лабораторная 1/Task2.py
> +total_book = round(info_vol//one_book_memory, )
Так я же использую данную функцию, на целочисленном делении для убирания знака после запятой, потому, что пайтон выдает зачем мне еще один знак после запятой то есть 3.0. Я понял, что вы имеете ввиду, но в данном случае это же вполне применимо, в целочисленном делении просто не может быть 3.75 и чтобы round округлил в большую сторону. Но даже так я не могу понять, что мне использовать для убирания знака после запятой, т.к. {numder:.0f} не работает почему-то. Может можно перевести в другой тип данных и так убрать знаки после запятой, то есть в целочисленный тип, я попробую. Да можно перевести в int и знаки после запятой убирают.

2024-10-19 19:16 UTC, rmushkin commented on Лабораторная 1/Task2.py
> +total_book = round(info_vol//one_book_memory, )
Да, вы правы :) Я увидел round и не полез глубже.)
+1 за `int`.

2024-10-19 19:18 UTC, rmushkin commented on Лабораторная 1/Task1.py
Хм, насчёт этого я должен немного подумать.

2024-10-19 19:23 UTC, ShizaIncorp commented on Лабораторная 1/Task1.py
Я только сейчас понял, что даже сравнение должно происходить с оператором if

2024-10-19 20:30 UTC, rmushkin commented on Лабораторная 1/Task1.py
В общем, да: вы правы. Я поспешил, и это можно решать хардкодом 😅

2024-10-19 20:31 UTC, rmushkin approved these changes
Принимается!

2024-10-19 20:32 UTC, ShizaIncorp commented on Лабораторная 1/Task1.py
Я вроде исправил, можете снова проверить?

2024-10-19 20:43 UTC, rmushkin commented on Лабораторная 1/Task1.py
Так это - проверил, принял.

2024-10-19 20:47 UTC, ShizaIncorp commented on Лабораторная 1/Task1.py
Благодарю :)

2024-10-22 21:29 UTC, rmushkin commented
Кстати, пожалуйста, дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-23 06:39 UTC, ShizaIncorp commented
Вроде, дал доступ, проверьте

2024-10-23 07:07 UTC, ShizaIncorp commented
Кстати, если заметил ошибку в курсе, вам отправить? Просто читаю конспект и там переменная указывает на None и используя оператор сравнения is добавляя условие not и сравния с None, должен быть false (проверил в проге) 
![image](https://github.com/user-attachments/assets/1f37a839-5212-4798-b246-35d245bb7e2f)

2024-10-23 17:03 UTC, rmushkin commented
Спасибо! Да тут и `not is` тоже в неправильном порядке стоит. Передам авторам курса!

2024-10-23 17:04 UTC, merged

2024-10-23 17:13 UTC, rmushkin commented
Кстати, зарепортить баг бы можете и сами! Нужно открыть issue и приложить туда вашу картинку с описанием:
https://github.com/hse-labs/DSH-PY101-issues/issues

2024-10-23 17:17 UTC, ShizaIncorp commented
А, отлично! :)

2024-10-23 18:31 UTC, ShizaIncorp commented
А у Вас вопросы по программе можно спрашивать? Просто я понять, не могу, как я понимаю в цикле for i должна приравниваться к первому элементу в students и становиться словарем, после я хочу обраться к значению лежащему в ключе grade и сравнить его с 3, но на этом моменте у меня ничего не получается. 
![image](https://github.com/user-attachments/assets/e9a6cbb4-cd86-427c-8cea-13ad1adf8522)

2024-10-24 08:15 UTC, rmushkin commented
Да, можно :)

Да, вы правы, всё должно работать именно так. И у вас всё правильно, а ошибка просто потому, что у вас нет кода, который бы выполнялся при удовлетрворении условию:

```python
students = [{"name": "Mary", "grade": 4}]

for student in students:
     if student['grade'] > 3:
         print(f"{student['name']} is nice")
```

2024-10-27 07:45 UTC, ShizaIncorp commented
Здравствуйте, а вы проверяете и 2 лабораторную? Просто я в среду отправил, а ее еще не проверили, а сегодня конец сдачи, как я понимаю.

2024-10-27 08:54 UTC, rmushkin commented
Здравствуйте! Официально я начинаю проверять после истечения мягкого срока. Фактически могу и раньше (как было с первой работой), но на это не стоит ориентироваться :)

2024-10-27 09:16 UTC, ShizaIncorp commented
А, хорошо :)